### ISSUE TITLE
erl process keeps running after atom crash

### ISSUE THREAD

**Issue by Hades32** [wende/autocomplete-elixir#13]
When the atom process hosting the erl process is ended unexpectedly then the erl process is never closed.

Maybe this happens because atom doesn't start Elixir directly but why Windows' conhost.exe. (Command line is: C:\Windows\system32\cmd.exe /s /c "elixir "C:\Users\Martin\.atom\packages\autocomplete-elixir\lib\alchemide\autocompleter\autocomplete.exs" "O:\Projekte\2048squared"" )

Windows 8.1 x64, Elixir 1.0.4, OTP 17.5

**Comment by iraasta** [comment]
That's new. I guess it's possible, but that's more Atom issue than this concrete package.
I use Atom's [BufferedProcess](https://atom.io/docs/api/v0.124.0/api/classes/BufferedProcess.html) and it's experimental so I guess they're working on that.
I'll try on my Windows machine when I'll get onto it

**Comment by Hades32** [comment]
I'm not sure if it was always like that, but now the erl.exe process stays there even of Atom is closed normally.

The issue here seems to be that elixir is started via a batch file wrapper, so while cmd.exe is closed, the rest is not.

Wouldn't it make sense to send a "Exit" command to the background process on close? Just hoping for a SIGINT/SIGTERM might not be the best way of handling a custom background process anyway...

**Comment by Hades32** [comment]
This doesn't seem to occur anymore with the most recent Atom Version.
