### ISSUE TITLE
fails to autocomplete popup at all and logs an error

### ISSUE THREAD

**Issue by brainlid** [wende/autocomplete-elixir#26]
System: Arch Linux
Elixir version: 1.1.1
Atom: 1.0.19
The beam.smp process is running but stays at 0% CPU.

There is an error when attempting to open the autocomplete at all. With Atom editing an Elixir mix project and the following file...

```elixir
defmodule TestingMixBuilds do
  def something do
    IO.puts "howdy"
  end
end
```

With the cursor on "IO.p" and pressing ctrl+space, no autocomplete is displayed. Opening the Atom Developer Tools, this is the error...

```
CLOSED 1, Last Error: ** (UndefinedFunctionError) undefined function: nil.current_env/0
    nil.current_env()
    lib/iex/autocomplete.ex:172: IEx.Autocomplete.env_aliases/0
    lib/iex/autocomplete.ex:159: IEx.Autocomplete.expand_alias/1
    lib/iex/autocomplete.ex:145: IEx.Autocomplete.expand_elixir_modules/2
    /home/mark/.atom/packages/autocomplete-elixir/lib/alchemide/autocompleter/autocomplete.exs:104: anonymous fn/5 in :elixir_compiler_0.__FILE__/1
    /home/mark/.atom/packages/autocomplete-elixir/lib/alchemide/autocompleter/autocomplete.exs:118: anonymous fn/3 in :elixir_compiler_0.__FILE__/1
```

The autocomplete feature currently doesn't work at all for me. Would love to get it working. :)

**Comment by wende** [comment]
Hello. Have You got autocomplete-plus installed?

**Comment by brainlid** [comment]
Yes. I previously checked all the requirements.

* autocomplete-plus (2.19.1) - a "core" Atom package that comes pre-installed. My only customization to this one was to change the "Keymap for Confirming a Suggestion" to "tab" from "tab and enter"
* autocomplete-snippets (1.7.1) - a "core" Atom package that comes pre-installed
* language-elixir (0.5.2) - installed. No customizations.

**Comment by gunnarhelgason** [comment]
I have the same issue when using Elixir 1.1.1. Seems to work fine with Elixir 1.0.5, though.

**Comment by Psvensso** [comment]
Ref: https://github.com/elixir-lang/elixir/commit/5e21d0d22dbbd55ff603763a31afe21885c12658

Go to your ~/.atom/packages/autocomplete-elixir/lib/alchemide/autocompleter/autocomplete.exs 

and add the autocomplete_server env var on the top. 

```
[env: [autocomplete_server: IEx.Server]]
```

**Comment by brainlid** [comment]
Thanks! That works great. Any chance you'll do a new release within the next week or so? I'm speaking at an Elixir meetup and wanted to include a highlight of your package. :)

**Comment by fourcube** [comment]
Thanks quickly providing a fix. 

+1 for a bugfix release.
