### ISSUE TITLE
Error even when disabled in Atom on Mac Yosemite

### ISSUE THREAD

**Issue by joel-regen** [wende/autocomplete-elixir#33]
I'm getting the following error when saving an elixir file (.ex):

(see attached file)

![screen shot 2015-11-11 at 12 42 48 am](https://cloud.githubusercontent.com/assets/1912095/11084782/57315190-880d-11e5-9dd2-c4052436f2ad.png)

**Comment by joel-regen** [comment]
test

**Comment by wende** [comment]
v1.5.5 Should fix the problem
Let me know if it occurs again

**Comment by joel-regen** [comment]
latest version in packages listing for autocomplete-elixir shows 1.5.4.

**Comment by wende** [comment]
Atom package servers are incredibely slow lately. I need to wait half an hours with a command running to reach the APM.
It should be ready in an hour or so
We need to wait in patience
Merry Christmas :gift:

**Comment by joel-regen** [comment]
On 12/19/15 7:18 PM, Krzysztof Wende wrote:
>
> Atom package servers are incredibely slow lately. I need to wait half 
> an hours with a command running to reach the APM.
> It should be ready in an hour or so
> We need to wait in patience
> Merry Christmas :gift:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wende/autocomplete-elixir/issues/33#issuecomment-166035299>.
>
thanks!
