### ISSUE TITLE
Highlight bug

### ISSUE THREAD

**Issue by tuvistavie** [wende/autocomplete-elixir#35]
Hi,
It seems that from 1.5.2 this package highlights anything below the cursor.
I am not sure if this is the wanted behavior, but I find this quite disturbing so
if it is, it would be good to have an option to disable it.
Removing [this line](https://github.com/wende/autocomplete-elixir/blob/master/lib/alchemide/doendmatcher.coffee#L19) fixes the issue.

**Comment by vladimir-tikhonov** [comment]
:+1: highlighting is very annoying. It's impossible to see what you are selecting and it highlight a lot of unnecessary things, like parentheses.
