### ISSUE TITLE
Cannot find module './alchemide/jumptodef'

### ISSUE THREAD

**Issue by vladimir-tikhonov** [wende/autocomplete-elixir#37]
In [this commit](https://github.com/wende/autocomplete-elixir/commit/782c4e70b6870f54e4d7a2226892110bec307403#diff-928881c673e15c7efaa5971e9a868be5R3) you added `require './alchemide/jumptodef'` but there is no such file in git, which causes package to crash.

**Comment by wende** [comment]
I forgot to add new files to git. Thanks for call!
