### ISSUE TITLE
Do/end matching is not strict enought

### ISSUE THREAD

**Issue by vladimir-tikhonov** [wende/autocomplete-elixir#38]
As you can see below, currently package highlight `do`/`end` pairs even if they are part of another word. I think it would be better to ensure that `do` and `end` keywords is surrounded by whitespaces before highlighting them.
![do_end_1](https://cloud.githubusercontent.com/assets/4998556/11918630/2c288e44-a74a-11e5-8b9b-d7c0792d3305.png)
![do_end_2](https://cloud.githubusercontent.com/assets/4998556/11918628/2c26f43a-a74a-11e5-9941-8f1c22d68eb7.png)

**Comment by vladimir-tikhonov** [comment]
:+1: thanks for your awesome work, @wende!

**Comment by vladimir-tikhonov** [comment]
There is new issue, howewer, as you see screnshot below.
![do_end_3](https://cloud.githubusercontent.com/assets/4998556/11924128/afe72ec0-a7bd-11e5-90a3-729f308f58b3.png)
New regex captures unnesesary whitespace symbols around the keywords (something like `do\n`) and many conditions below (for example [here](https://github.com/wende/autocomplete-elixir/blob/58332ee353853754800a7f55e96f8e8e8ff534fd/lib/alchemide/doendmatcher.coffee#L27)) stop working.

**Comment by wende** [comment]
Yes. I made mistake by commiting without checking.
The problem right now is, that if it matches `\n` then it extends range by one row. But if it's any other character it extends by column. 
I've got to think of something clever to fix that

**Comment by wende** [comment]
I didn't realize that such thing as word boundary (`\b`) exists in regex. Well what do you know! :grinning: 
v1.5.12 should fix that.
Merry Christmass :gift:

**Comment by vladimir-tikhonov** [comment]
@wende thanks, and you too :smile:
