### ISSUE TITLE
Autocomplete doesn't show up

### ISSUE THREAD

**Issue by hdcos** [wende/autocomplete-elixir#42]
Hi I install the package with apm (can't find it using the setting view)
I have all the dependencies installed and yet I can't use the autocomplete. Before the autocomplete of language-elixir worked and now it doesn't work. When I uninstall the plugin the autocomplete of language-elixir rework.

Have I missed something? I have autocomplete-plus installed and language elixir installed. I am running on a ubuntu linux instance 14.04.last
When I add the path of the binary nothing work too. (/usr/local/bin/)

atom version: 1.3.2

**Comment by victorlcampos** [comment]
+1

**Comment by wende** [comment]
I'm using Ubuntu 14.04 myself and haven't got any problems. 
Could you launch atom in Developer Mode and SS me the console?

**Comment by wende** [comment]
I've added Troubleshooting to the README.md file
Please check out if anything works for you from there

**Comment by nulian** [comment]
I had the same problem what I found out after going developer mode is that the plugin doesn't give a warning message if you haven't correctly entered the erlang bin directory. I had entered the folder 1 up from it.

**Comment by hipertracker** [comment]
Autocomplete **works on Windows 10, it doesn't show up on O SX** El Capitan. I have the save versions of Atom and libs.
