### ISSUE TITLE
Upgraded to Atom 01.18.0 and now this crashes it.

### ISSUE THREAD

**Issue by komizutama** [wende/autocomplete-elixir#89]
I was getting the  "This socket is closed" error others have listed. 
I upgraded to 1.18.0 as suggested. And atom began hanging and then crashing with open projects. 
First, an alert will appear that says, "Atom is not responding would you like to close the window." 
Then, upon closing it another pops up saying the editor has crashed.  There are three options "Keep it open" "reload" and "close window" the first two do nothing, the last sort of keeps it alive, but then I have to force quit. 
Disabling this plugin stops the problem.

**Comment by wende** [comment]
@komizutama 
autocomplete-elixir is deprecated and no longer works with newer versions of Atom.
I recommend https://github.com/msaraiva/atom-elixir/ instead.
It's officially supported by Platformatec and is much more reliable

**Comment by komizutama** [comment]
@wende
Thank you!
